### ISSUE TITLE
[Suggestion] Config options for crate controls

### ISSUE THREAD

**Issue by ProspectPyxis** [Funwayguy/BarrelsDrumsStorageAndMore#12]
While the barrel control changes in the latest version are nice when preparing locked crates, it makes trying to pull out a small amount of items from a crate a bit awkward since you have to deliberately delay a bit between each click. I suggest adding config options for the amount of delay between clicks or being able to switch to the old sneak control scheme.

**Comment by Funwayguy** [comment]
_sigh_

I think this is the 6th or 7th request for a control change since I started making this thing. I figured it wasn't that big a deal to just put the extra items back in after you separate out what you needed. The delay is currently enforced server side so a config would be that simple. To move it client side I'd need to rework a bunch of stuff and honestly I'm trying to avoid changing much while SF4 is still stabilizing.

**Comment by ProspectPyxis** [comment]
Fair enough. I guess it'll take some time getting used to.

**Comment by Mac15001900** [comment]
>  while SF4 is still stabilizing

So this might be a feature in the future? If so, I'd like to add to this suggestion the ability to fully customise it: binding left or right click (with sneaking or not) to each of 'put in item', 'take 1 item', 'take 1 stack'. That should stop people complaining about control changes.

**Comment by Funwayguy** [comment]
Added in build 0.0.24 (after even more complaints >_>). No idea when SF4 will update to this version but it's on Curse if you _really_ want. On a server things may be slightly slower to dispense now that it has to query the client every time.
